/*
 * Copyright (c) 2025, Stephen Mgbeojikwe. All rights reserved.
 * For license. See license.txt
 */


export const imageIconPack = {
    splashicon: require('@assets/images/splashicon.png'),
    mainlogo: require('@assets/images/mainlogo.png'),
    eyeopen: require('@assets/images/eyeopen.png'),
    eyeclose: require('@assets/images/eyeclose.png'),
    brightness: require('@assets/images/brightness.png'),
    camera_add: require('@assets/images/camera_add.png'),
    loginBackground: require('@assets/images/loginbackground.png'),
    keyboard_outline: require('@assets/images/keyboard_outline.png'),
    picture_plus: require('@assets/images/picture_plus.png'),
    smart_orange_icon_with_user: require('@assets/images/smart_orange_icon_with_user.png'),
    arrowLeft: require('@assets/images/arrowleft.png'),
    map_location: require('@assets/images/map_location.png'),
    list: require('@assets/images/list.png'),
    family_signboard: require('@assets/images/family_signboard.png'),
    vecteezy_city: require('@assets/images/vecteezy_city.png'),
    smart_modern_minimalist_house: require('@assets/images/smart_modern_minimalist_house.png'),
    share: require('@assets/images/share.png'),
    map: require('@assets/images/map.png'),
    offer: require('@assets/images/offer.png'),
    logout: require('@assets/images/logout.png'),
    increment: require('@assets/images/increment.png'),
    decrement: require('@assets/images/decrement.png'),
    check_circle_fill_green: require('@assets/images/check_circle_fill_green.png'),
    cancel: require('@assets/images/cancel.png'),
    lightbulb_circle_fill_yellow: require('@assets/images/lightbulb_circle_fill_yellow.png'),
    lisitingphoto: require('@assets/images/lisitingphoto.png'),
    uncheck: require('@assets/images/uncheck.png'),
    recaptchalogo: require('@assets/images/recaptchalogo.png'),
    services_requests: require('@assets/images/services_requests.png'),
    checked: require('@assets/images/checked.png'),
    arrow_right: require('@assets/images/arrow_right.png'),
    excmark: require('@assets/images/excmark.png'),
    language: require('@assets/images/language.png'),
    moon_line: require('@assets/images/moon_line.png'),
    safety_certificate_line: require('@assets/images/safety_certificate_line.png'),
    notification_newdot_line: require('@assets/images/notification_newdot_line.png'),
    like: require('@assets/images/like.png'),
    applogo: require('@assets/images/applogo.jpg'),
    loginbackground: require('@assets/images/loginbackground.png'),
    darkbackground: require('@assets/images/darkbackground.png'),
    appicon: require('@assets/images/appicon.jpg'),

    auction_line: require('@assets/images/auction_line.png'),
    hand_heart_line: require('@assets/images/hand_heart_line.png'),
    chevron_right_outline: require('@assets/images/chevron_right_outline.png'),
    services: require('@assets/images/services.png'),
    home: require('@assets/images/home.png'),
    redo: require('@assets/images/redo.png'),
    success: require('@assets/images/success.png'),
    pincode: require('@assets/images/pincode.png'),
    notification: require('@assets/images/notification.png'),
    list_add: require('@assets/images/list_add.png'),
    search: require('@assets/images/search.png'),
    avatar_small: require('@assets/images/avatar_small.png'),
    check_mark: require('@assets/images/check_mark.png'),
    faceid: require('@assets/images/faceid.png'),
    file_locked_line: require('@assets/images/file_locked_line.png'),
    news_2_line: require('@assets/images/news_2_line.png'),
    fingerprint: require('@assets/images/fingerprint.png'),
    file_search_line: require('@assets/images/file_search_line.png'),
    lifebuoy_line: require('@assets/images/lifebuoy_line.png'),
    hand_line: require('@assets/images/hand_line.png'),
    user_line: require('@assets/images/user_line.png'),
    wallet_line: require('@assets/images/wallet_line.png'),
};


export type ImageIconPackType = keyof typeof imageIconPack;
